# Copyright 2023 HM Revenue & Customs
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

include "backend.conf"

appName=eps-message-renderer

# Router
# ~~~~~
# Define the Router object to use for this application.
# This router will be looked up first when the application is starting up,
# so make sure this is the entry point.
# Furthermore, it's assumed your route file is named properly.
# So for an application router like `my.application.Router`,
# you may need to define a router file `conf/my.application.routes`.
# Default to Routes in the root package (and conf/routes)
# !!!WARNING!!! DO NOT CHANGE THIS ROUTER
play.http.router=prod.Routes

play.modules.enabled += "uk.gov.hmrc.play.bootstrap.HttpClientV2Module"

# Logger
# ~~~~~
# You can also configure logback (http://logback.qos.ch/), by providing a logger.xml file in the conf directory .

# Root logger:
logger.root=ERROR

# Logger used by the framework:
logger.play=INFO

# Logger provided to your application:
logger.application=INFO

# Microservice specific config

txmonitoring {
    enabled=true
    traceRequests=true
}

microservice {
    services {
        timeout = 5 seconds
        delay-response = 2 seconds
        protocol=http

        auth {
            host=localhost
            port=8500
        }

        preferences {
          host = localhost
          port = 8025
        }

        hods-adapter {
          host=localhost
          port=9412
        }

        email {
          host=localhost
          port=8185  # DIGITAL_CONTACT_STUB
        }

        mobile-push-notifications-orchestration {
          host = localhost
          port = 8257
        }
    }
}
